[build]
builder = "nixpacks"
buildCommand = "cd ../.. && npm install && cd apps/worker && npx prisma generate && npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
