[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["cd ../.. && npm ci"]

[phases.build]
cmds = ["cd ../.. && npx turbo run build --filter=@shoppable-webinar/web"]

[start]
cmd = "npm run start"
